#!bin/sh

#Script de sintaxe IF/ELSE

clear
date

echo "Digite um numero"
read numero

if [ "$numero" -lt "50" ];then

echo "O numero eh menor que 50"

else

echo "O numero eh maior (ou igual) que 50"

fi
